export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  LightTextDesc: true,
  topLine: "Premium Heart",
  headLine: "Unlimited love for Sweetie",
  description: "everything for my sweetie",
  buttonLabel: "Beginning",
  imgStart: false,
  img: require("../../images/undraw_Reading.svg").default,
  alt: "my love",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  LightTextDesc: false,
  topLine: "Unlimited love",
  headLine: "Unlimited love for Sweetie",
  description: "everything for my sweetie",
  buttonLabel: "Lear more about us",
  imgStart: true,
  img: require("../../images/undraw_Social_life.svg").default,
  alt: "my love",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "services",
  lightBg: true,
  lightText: false,
  LightTextDesc: false,
  topLine: "Premium Heart",
  headLine: "Unlimited love for Sweetie",
  description: "everything for my sweetie",
  buttonLabel: "Beginning",
  imgStart: false,
  img: require("../../images/undraw_Appreciation.svg").default,
  alt: "my love",
  dark: false,
  primary: false,
  darkText: true,
};
